### ISSUE TITLE
[Profession] JC - Thorium Setting craft - amount of material

### ISSUE THREAD

**Issue by 2d4you** [SunwellWoW/Sunwell-TBC-Bugtracker#2519] opened 2018-12-05 16:10 UTC
Description: In the description of the skill says about 1 thorium bar for 1 setting, but after craft spent 3 bars instead 1

How it works: 
Amount of material - 3 Thorium bar for 1 setting

How it should work: 
Amount of material - 1 Thorium bar for 1 setting

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment] 2018-12-05 17:55
Did you remove your cache? It's patch change actually.

**Comment by 2d4you** [comment] 2018-12-05 18:14
Yeah, just now removed and nothing changed.

**Comment by Fuzedknight** [comment] 2018-12-07 01:04
Confirmed it is still bugged for me. https://puu.sh/CdHXP/d4651954ae.mp4

**Comment by 2d4you** [comment] 2018-12-07 08:30
Thanks for video mate

**Comment by Wojtyas** [comment] 2018-12-07 10:49
It's intented due patch changes. It needed 3x thorium bar till Black Temple release. What's bothering me that tooltip will probably always show 1x requirement :( in that case I think it may be reverted, I will let you know.
https://www.wowhead.com/spell=26880/thorium-setting#comments
![image](https://user-images.githubusercontent.com/22802214/49650274-fa9e0d80-fa2b-11e8-8ae2-94042e14fba7.png)

**Comment by Reykjavikshore** [comment] 2018-12-08 11:27
thanks for that link i will try it now

**Comment by Reykjavikshore** [comment] 2018-12-08 11:28
okay it working but its visual bug in the jc window now i see only 1 bar needed for 1 not 3 like its works

**Comment by jbwilson11** [comment] 2018-12-08 15:49
Quick question -- why is this intended?  Isn't this server on patch 2.4.3?

"Good morning to all those interested in our 2.4.3 realm, called Nightbane!

It's launch date will be announced 4th November, around 20:00."
http://sunwell-community.com/index.php?/topic/4764-periodic-survey-nightbane-summary/

**Comment by sinfer** [comment] 2018-12-11 21:35
so its not a bug? made me scream _a little bit_ inside my head when i came back from smoke and i should have had 57 thorium settings but now i have 17.  RIP 3 stacks of thorium 2018-2018

**Comment by Wojtyas** [comment] 2018-12-12 11:47
We'll revert it. No sense to keep it with 3x when noone see that ;d

**Comment by sinfer** [comment] 2018-12-12 14:53
Any possibility to get back the lost mats? 😅 poor jc here who lost mats worth of 30g.. :(

**Comment by lohkiiodin** [comment] 2018-12-19 21:43
Any update on when this will be fixed?

**Closed as completed** 2019-01-04 12:26 UTC
Labels: Professions, Intended, Fixed and Implemented.
