### ISSUE TITLE
Elemental mastery in macro

### ISSUE THREAD

**Issue by Doz-o** [SunwellWoW/Sunwell-TBC-Bugtracker#3028] opened 2018-12-10 03:29 UTC
Description: When i use elemental mastery in macro it gets used and goes away without a spell cast. When i use elemental mastery by itself i spam click and it does not go away.

macro
/cast Elemental Mastery
/use Vengeance of the Illidari
/use Blood Fury(Racial)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Doz-o** [comment] 2018-12-10 04:49
When i changed elemental mastery to the last spell in sequence it now works fine

**Comment by Avishai97** [comment] 2018-12-10 11:47
the issue is that elemental mastery gets consumed upon clicking any spell, item, whatever

**Comment by Wojtyas** [comment] 2018-12-10 12:02
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2450
Will be fixed today/tommorow.

**Closed as completed by Wojtyas** 2018-12-10 12:02 UTC
Labels: Duplicate
