### ISSUE TITLE
Rapid Killing Hunt MM talent doesn't work

### ISSUE THREAD

**Issue by Madeska1** [SunwellWoW/Sunwell-TBC-Bugtracker#3244] opened 2018-12-12 10:35 UTC
Description: Rapid killing talent doesn't work

How it works: Don't work

How it should work: When you final kill mob or character, this talent proc.

Source (you should point out proofs of your report, please give us some source): Playing hunter

**Comment by presstmoded** [comment] 2018-12-12 11:07
Yeah, it procs randomly from time to time (as if it had some inner cooldown which it should NOT), and is not consumed by any shot other than Aimed Shot (should be consumed by Arcane Shot and Auto Shot aswell as Aimed Shot).

**Comment by Wojtyas** [comment] 2018-12-12 11:18
Hmm, maybe it procs only when actually hunter does final hit which kills target w/o respect when there are other pt/raid members ;O should proc when target dies no matter who killed it when hunter's fightning against it as well

**Comment by presstmoded** [comment] 2018-12-12 11:56
It just procced from a kill made all by my pet:

![obraz](https://user-images.githubusercontent.com/21221088/49867987-5ab9f880-fe0c-11e8-9721-99c64b54a6eb.png)

and sometimes it just do not proc at all:

![obraz](https://user-images.githubusercontent.com/21221088/49868137-cd2ad880-fe0c-11e8-8933-f9ca082ffd37.png)

Keep in mind it worked perfectly before, I've noticed problems with it since like yesterday or maybe 2 days ago. Apart from being procced (or not procced) by pet/hunter, once it actually proc, it's still not consumed by any other shot than Aimed Shot. Sometimes it's not consumed even by Aimed, I've got no idea how it works, seems to be quite random...

I am aware of the fact, that it's just a minor thing, but 20% stronger opener is rather important for a hunter, while farming, leveling etc.

**Comment by Zarant** [comment] 2018-12-12 13:24
> On Kill Effects: Items and abilities that trigger on killing an enemy will no longer trigger on using an ability that kills your pet. 

http://wowwiki.wikia.com/wiki/Patch_2.3.0


> Abilities and items that are triggered when you kill a target are also now triggered when your pet kills a target. 

http://wowwiki.wikia.com/wiki/Patch_2.1.0

**Comment by presstmoded** [comment] 2018-12-12 13:32
Rapid Killing is being triggered here on Sunwell - Nightbane randomly. Sometimes pet triggers it, sometimes not. Sometimes it procs from hunter killing a mob (that yes, yields xp or honor), sometimes not. When it procs, sometimes it's consumed by Auto Shot/Arcane Shot/Aimed Shot, sometimes you can hit the target with any of those skills for all 20seconds of the buff and it won't be consumed. Sometimes it works fine, and sometimes (which just blows my mind really) it won't be consumed by Auto Shot, or Arcane Shot, but only by Aimed Shot. You can't make this stuff up.

And by the way, that 2.3.0 change was for warlocks to not gain on kill effects after sacrificing pet.

**Comment by akrom23** [comment] 2018-12-12 18:10
Can't confirm. Proc for me everytime and consumed everytime by these spells.

**Comment by Slykz** [comment] 2018-12-14 13:41
Duplicate of #2948

**Comment by Jonsbe** [comment] 2018-12-18 17:38
Well, for me the buff isnt consumed never. Never had it proc off from a shot.

**Comment by Zamesi** [comment] 2018-12-23 16:15
Procs randomly and isn't consumed by any of the shots mentioned.

**Comment by alucardcsn** [comment] 2018-12-26 22:09
This talent is not working properly. It's an important talent.

**Comment by akrom23** [comment] 2019-01-02 11:22
Consumed by Aimed Shot:
![wowscrnshot_010219_121707](https://user-images.githubusercontent.com/1035215/50589953-02b16780-0e89-11e9-870c-597c30b5e1a9.jpg)

Consumed by Arcane Shot:
![wowscrnshot_010219_121809](https://user-images.githubusercontent.com/1035215/50589957-080eb200-0e89-11e9-9fc9-c70ea671803f.jpg)


Auto shot does not work.

**Comment by flapse32** [comment] 2019-01-05 14:32
So when is this gonna go live? Its pretty critical bug.

**Closed as completed** 2019-01-11 16:12 UTC
Labels: High Priority
