### ISSUE TITLE
Druid Shape Shifting Delays

### ISSUE THREAD

**Issue by Meerkhat** [SunwellWoW/Sunwell-TBC-Bugtracker#3212] opened 2018-12-11 21:40 UTC
Description:
Shifting Delays 

How it works: 
When Shifting from Human form to Cat Form the delay is somewhat normal, but when you shift from cat form to human for there is a noticeable delay that's not suppose to be there it doesn't happen every time but enough to be a problem. The delay is to long compared to Retail TBC as well as Other servers ive been on.

How it should work: 
When shifting from Cat for to human for should have the same delay as Human to feral. Not sure how else to describe it.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/4a7de90c1e7d7d2262048a93c5eb5313
https://gyazo.com/8a877578a275605266b131c4ecdecb00
https://gyazo.com/069211303c9f7ef47fee0d793a78b3a6

**Comment by Meerkhat** [comment] 2018-12-11 21:41
Not sure if it's just me that notices the issue but I've Main spec'd Feral Dps on Several other serves and never noticed the delay so maybe its just different on other servers.

**Comment by Jseay1313** [comment] 2018-12-12 00:56
Here's the problem - when you are shifting out of forms on Sunwell it is activating a GCD. Druids are only supposed to get a GCD when shapeshifting to another form I.E Human to Cat or Human to Bear. You're not supposed to get a GCD when you shift out of forms. I play a druid and I didn't notice this the entire time despite it feeling terrible until I saw this post and looked at old videos.

Source:: https://www.youtube.com/watch?v=dc0WrORiHmM all over this video 
https://www.youtube.com/watch?v=tS-xtpZMC8A 3:09
https://www.youtube.com/watch?v=onimVSWwZLg You can see here that shifting from form to form activates a GCD as intended, but shifting out of forms to human (or moonkin which is also considered human) does not
https://www.youtube.com/watch?v=Apw9z0ifN_c starts in cat form shifts out and no gcd

**Comment by akrom23** [comment] 2018-12-12 16:06
@Meerkhat When I click on form to shift out, there is no gcd activated. Are you using some kind of macros?
On 1. screen I see no GCD.
On 2. and 3. you started casting spell - that's why gcd activated.

**Comment by Meerkhat** [comment] 2018-12-12 17:01
The Shape shifting is bound to my mouse wheel that is it. Nothing macro'd with the Shifting.

**Comment by YoshGit** [comment] 2018-12-25 14:15
I’m noticing this for a lot of spells without gcd on and off. For example when I cast bestial wrath or feign death it often fails to go off saying “another action in progress”. Sometimes I need to spam it 5-10 times before it goes off. Alternately I never get this issue with rapid fire. Impossible to say for sure since we can’t see the source code but maybe there is some sort of queueing or locking going on in the background?

Edit: #2326 could be related - seemingly random delays where there shouldn’t be?

**Comment by MiekZer** [comment] 2018-12-27 22:20
I have the feeling it's due to server tickrate/delay and will never be fixed with that "no spell batching" core.
Unless they drastically upgrade their tickrate / reduce their delay so we have a refresh of the packets every 1millisecond or less

**Comment by YoshGit** [comment] 2018-12-27 22:25
Let’s hope not - nothing ruins the game better than mashing spells and having them not go off...

**Comment by YoshGit** [comment] 2018-12-28 15:47
Was digging through some old hunter threads and if this is a spell queueing issue maybe these kind of delays are blizzlike (still super annoying though)? Based on comment 2707 http://web.archive.org/web/20080304041604/http://elitistjerks.com:80/f31/t11420-hunter_beast_mastery_bible/p109/

**Comment by akrom23** [comment] 2019-01-07 19:43
Any news? I don't see any delay there.
On the third one it looks like a lag.

**Comment by Meerkhat** [comment] 2019-01-07 19:45
I didn't experience any lag during those clips. What you are seeing is the
delay. But no, it sucks when I'm using healing and I get swapped to human
form there is still that delay

**Comment by akrom23** [comment] 2019-01-07 19:47
@Meerkhat I was not able to reproduce it on local server.
But I will not give up! I will try!

**Comment by akrom23** [comment] 2019-01-08 19:35
Tested on live server - still no delay.

**Comment by akrom23** [comment] 2019-02-27 18:05
@Meerkhat @Jseay1313 @YoshGit @MiekZer Any news?

**Comment by koostosh** [comment] 2019-03-12 10:10
Could not reproduce on live server nor locally, only delay experienced is server lag.

**Closed as completed by koostosh** 2019-03-12 10:10 UTC
Labels: Invalid, Question
