### ISSUE TITLE
[Hunter][Spell] Arcane shot rank 6

### ISSUE THREAD

**Issue by Zarant** [SunwellWoW/Sunwell-TBC-Bugtracker#2672] opened 2018-12-07 00:58 UTC
https://i.imgur.com/N06k4cZ.png

As the tooltip reads, it should remove 1 magical effect from the target, right now only rank 7 and above are capable of dispelling magical effects.

**Comment by kinglobster** [comment] 2018-12-07 15:27
this is weird, my rank6 dispels without any problems

**Comment by kinglobster** [comment] 2018-12-07 17:44
this can be closed as everything is working as intended https://imgur.com/a/CMpx7PB

**Closed as completed** 2019-01-21 16:44 UTC
Labels: Invalid
