### ISSUE TITLE
[Druid][Talent] Subtlety

### ISSUE THREAD

**Issue by notsofamous** [SunwellWoW/Sunwell-TBC-Bugtracker#409] opened 2018-09-15 15:52 UTC
Decription: 
Supposed to reduce dispel resistance by 30%. Tried to dispel 90 times, only 7 were resisted. 

Unsure if all spell resistance mechanics/talents might be affected or just this one.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
http://db.hellfire-tbc.com/?spell=17122

**Comment by lukaasm** [comment] 2018-09-23 11:46
Talent works fine, but the issue is related to:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/253

because if aura has multiple effects, each effect is treated as a unique entry for dispell roll.
It will be fixed later with the introduction of SpellAuraHolder

**Closed by lukaasm** 2018-09-23 11:46 UTC
Labels: class, druid
