### ISSUE TITLE
Gas clouds in Nagrand are broken as of 14 hours ago

### ISSUE THREAD

**Issue by peteyo** [SunwellWoW/Sunwell-TBC-Bugtracker#4280] opened 2019-02-06 01:00 UTC
Description: 
The gas clouds in Nagrand are no longer working as intended as of earlier this morning Feb 5th 2019. They were working fine up until 10 am server this morning and sometime between now and then a change was implemented on the server which inadvertently messed up how the gas clouds are functioning both in terms of their spawning and their patrolling. 

How it works:  
Right now there are 12 gas cloud locations in Nagrand. When one is looted it does not respawn after 45 minutes (or even after two hours which is as long as I camped one single spawn for to confirm that something was not working correctly). It looks like they do respawn- not in the location they were looted in- but in some random location in the map. 
Additionally, the spawn east of Telar is supposed to patrol in a triangle between Telar, Burning Blade Ruins, and Kil Sorrow Fortress- instead it spawns in the middle of triangle in the mountains and does not move at all.

How it should work: 
Each of the 12 spawns in Nagrand should be set to its own individual 45 minute respawn timer. That means that exactly 45 minutes to the second after you loot a cloud it should respawn in that exact same location. This isn't the case anymore. 
Additionally, the spawn directly east of Telar should patrol from Telar to Kill Sorrow fortress to Burning Blade ruins and back to its original spawn. Instead it spawns somewhere in the middle of that triangle up in the mountains in a location where it is unlootable by anyone and does not patrol at all.

Source (you should point out proofs of your report, please give us some source): 
I don't have any source except that me and my friends sat at 4 different spawns and camped them for nearly 2 hours today to confirm that it was not working as intended.
The spawns were confirmed to be working at 10 AM Server time on FEB 5 2019, and sometime between then and 10 PM server time of the same day a change was made that affected these spawn timers. You can verify this by spawning a cloud, looting it, and seeing if it respawns in 45 minutes.

Edit: I heard that on another server when the speed of Illidans eye beam was changed one day that the nagrand gas clouds gained 500% movement speed and were unlootable until they were fixed. Maybe something similar happened with a change made in the last 14 hours? 

Edit2: The spawn that I camped today was the one on the rock above the throne of elements. This spawn does not patrol at all- it just floats in the air above the rock so there is no way that it could have been spawned and patrolling around without me noticing it. Similarly my 3 friends that helped confirm this with me each camped a stationary spawn and not a patrolling one.

**Comment by lordazurescens** [comment] 2019-02-06 02:23
Tested a spawn for 1hour 30mins definitely are not working like they use too.

there is also a few in locations unreachable.

**Comment by Diobloxx** [comment] 2019-02-06 02:29
Waited for an hour at a spawn point. Confirmed they are not working as intended

**Comment by Devrak** [comment] 2019-02-06 04:12
There should be more than 12 spawns and exact 45 min timer does not seem blizzlike I think this needs alot more research

**Comment by mchayes** [comment] 2019-02-06 09:56
It's seems much more likely that a fixated location and spawnrate is a private server thing. Blizzard made much more use of a randomized spawn inside of a node-hub. 
So you'd have a hub of lets say 5 spawn nodes, but it'd only be able to spawn in 1 of 5 at a time. You can see something similar to flamecap, khorium.

**Comment by Bugadin** [comment] 2019-02-06 11:27
Why the hell only for the air clouds? I mean, does Sunwell pretend to fuck up every way of making gold? They have nerfed everything!

**Comment by lordazurescens** [comment] 2019-02-06 17:56
Can we get some clarification on this? 

They are also spawning in locations that you can't even reach. there are 2 clouds that can't be taken. they hover about 6x the distance that you can cast mote extractor at. above the floating islands. they do not patrol down.

**Comment by Wojtyas** [comment] 2019-02-06 18:50
Sir Dootz assigned this ticket to himself so I bet he's working on it ;) Stay tuned pals, probably will get fixed soon.

**Comment by lordazurescens** [comment] 2019-02-06 19:00
The Gas cloud at 69.5 69.5  has been in an area that prevents extraction. Since the changes occurred. almost 36hours.

Spawn locations needs to be fixed or removed.

GM currently won't de-spawn it. so its preventing others from spawning.

**Closed as completed** 2019-02-07 22:37 UTC
Labels: Object, Fixed and Implemented.
