### ISSUE TITLE
Shadowmeld bug

### ISSUE THREAD

**Issue by Gedlund** [SunwellWoW/Sunwell-TBC-Bugtracker#19] opened 2018-08-01 12:10 UTC
Decription: 
Attacking a mob with a spell, for example Wrath on druids and then pressing Shadowmeld will cause the mob to bug out. 

How it works: 
Attacking a mob with a spell, for example Wrath on druids and then pressing Shadowmeld will cause the mob to bug out. 

How it should work: 
Mob should reset fully and attack you once you begin attacking again, or it should put you in combat quicker not allowing you to cast shadowmeld while the projectile is flying, 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment] 2018-08-26 08:04
Cannot reproduce.
Mob properly reset and when is attacked again, it's chasing me.
Combat is put when spell hits targets, not when ii is launched.

**Comment by Nadiirr** [comment] 2018-09-20 08:49
Working for me. 
I attacked mob with wrath. 
Pressed shadowmeld while projectile was in air. 
Mob reset normally. 

Closing.

**Closed by Nadiirr** 2018-09-20 08:49 UTC
Labels: General/Core, class, priest, question
