### ISSUE TITLE
rogue vanish

### ISSUE THREAD

**Issue by smlk87** [SunwellWoW/Sunwell-TBC-Bugtracker#2700] opened 2018-12-07 08:51 UTC
Description: still there is a bag after the restart on the server . combat vanish stealth out..Basicly when you enter combat and then you vanish to combat out you go in steath mode but when you go anstealth the stealth button is gray and you cant press it to go again in stealth.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Foosiq** [comment] 2018-12-07 13:27
This is duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2605 , use search first man.

**Closed as completed** 2018-12-07 14:01 UTC
Labels: Duplicate, Fixed and Implemented.
