### ISSUE TITLE
[Hunter] Suggestion: Increase pet experience.

### ISSUE THREAD

**Issue by ujellyx** [SunwellWoW/Sunwell-TBC-Bugtracker#2376] opened 2018-12-04 07:02 UTC
Description: 
As of right now it's hard for a pet to catch up with the experience. I'd like to suggest increasing the received experience by the pet a little.

How it works: 
I tamed a Ravager (level 16) at level 26. With normal questing and a little grinding even I am now level 34 while my pet is still only level 23... It just can't keep up with the 2x exp-rate somehow...

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealestMcCoy** [comment] 2018-12-05 01:02
my pet has fallen 4 levels behind me and was my level at the start

**Comment by Darrgoth** [comment] 2018-12-05 05:12
I agree I have to tame a new pet every few levels.

**Comment by ujellyx** [comment] 2018-12-05 09:00
Update: I'm now level 40 and my pet is still at level 29... something needs to be done about the pet-experience...

**Comment by Lunasoll** [comment] 2018-12-06 20:25
I can confirm. I think hunter pets didn't get 2x xp rate. Heavily falling behind their masters in terms of level.

**Comment by cokolele** [comment] 2018-12-11 14:30
Do you still have a problem with outleveling your pet ? I think they fixed it.

**Comment by Darrgoth** [comment] 2018-12-11 14:31
I grind alot more now so I dont have a problem, the main problem was because of questing etc. 
    On Tuesday, December 11, 2018, 9:30:28 AM EST, cokolele <notifications@github.com> wrote:  
 
 
Do you still have a problem with outleveling your pet ? I think they fixed it.

**Comment by ujellyx** [comment] 2018-12-11 14:36
Nah I doubt they fixed it. I'm almost 70 now and my pet is still at 64 (tamed at 62).

**Comment by siof** [comment] 2018-12-12 12:29
For me it seems to work as should but if you have any informations that on TBC pet XP calculations had different formulat please post links with proofs. Below are informations how it is working currently.

All values are examples AFTER modifications by rates/party/etc not real data
Pet is getting XP ONLY from killing and not from explore/quests.

Consider that player should get 100 experience (after modifications by rates).

There are 2 possible situations for calculate pet xp from this value and one huge modifier to it which will be described last.

First situation: Hunter is not in party (solo with pet)
If hunter is not in party then pet is getting 100% of experience which was calculated for player.
In our example situation if player will get 100 XP then pet will get 100 XP (if player is not in party).

Second situation: Hunter is in party
If hunter is in party then pet is getting 50% of experience which was calculated for player.
In our example situation if player will get 100 XP then pet will get 50 XP (if player is in party).


Those are two main possible situations which modifies XP get by pet, but as i said in the beginning there is also one huge modification to them.

Pet's experience gain is not modified by player rest bonus. 

If player has rest bonus then player will get other values than written above.

Lets consider first situation again with rest bonus:
If XP calculated for player was 100 then with rest bonus he will get 200. But as i said before Pet's experience gain is not modified by rest bonus so pet will get only 100 XP.

Lets consider second situation again with rest bonus:
If XP calculated for player was 100 then with rest bonus he will get 200 but pet only 50 XP (because base 100XP/2 = 50).

Here is video which shows values got by pet without rest bonus on x2 server rates with and without .blizzlike command active:
[https://drive.google.com/file/d/1P2prevP_6Wk7H1-6Pue_XSgEmn56EXbO/view](url)


If you will have proofs that those calculations are incorrent from TBC point of view please share links with us.

**Comment by siof** [comment] 2018-12-12 12:30
closing this one and will continue in #2805

**Closed as completed by siof** 2018-12-12 12:30 UTC
Labels: Duplicate, Invalid
