### ISSUE TITLE
crashes in blade"s edge mountains

### ISSUE THREAD

**Issue by kaozin** [SunwellWoW/Sunwell-TBC-Bugtracker#3644] opened 2018-12-19 16:34 UTC
Description: Stuck in Blades edge mountains Crashing constantly i cant log my character kao 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Laekoth** [comment] 2018-12-20 01:20
the location is approx. 45, 73

**Comment by jbwilson11** [comment] 2018-12-28 03:05
Duplicate of https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3643

I have a error-crash text file attached to issue 3643

**Closed as completed** 2019-01-20 20:03 UTC
Labels: Duplicate, General/Core, High Priority
