### ISSUE TITLE
Casting through pillars

### ISSUE THREAD

**Issue by mrnorr** [SunwellWoW/Sunwell-TBC-Bugtracker#1227] opened 2018-11-06 18:31 UTC
Decription: 
Nagrand Arena (Ring of Trials) can cast through pillars

How it works: 
Nagrand Arena (Ring of Trials) can cast through pillars

How it should work: 
You should not be able to cast spells through a pillar object

Source (you should point out proofs of your report, please give us some source): 
Dueling in the Ring of Trials now with a mage on the beta server

**Comment by akrom23** [comment] 2018-11-06 18:49
And what about the arena?

**Comment by mrnorr** [comment] 2018-11-06 18:54
What I'm saying is is that in that arena, open world, non-instanced, the mage was able to cast full cast Frostbolt on me and hit me through the four pillars, at that location

**Comment by akrom23** [comment] 2018-11-06 19:46
Okay. Can you test it on Nagrand Arena (arena)?

**Comment by mrnorr** [comment] 2018-11-06 19:51
Sure thing, hopefully can get some others to join so I can get in the instanced version

-------- Original Message --------

**Comment by akrom23** [comment] 2018-11-07 07:40
Tell me, how you get there?

**Comment by akrom23** [comment] 2018-11-07 07:45
Cannot reproduce on open beta. Some screenshots please?

**Comment by akrom23** [comment] 2018-11-07 08:54
Will be fixed after restart on SSC realm..

**Closed** 2018-11-07 21:50 UTC
Labels: MMaps/VMaps
