### ISSUE TITLE
Druid changing shapeshift forms

### ISSUE THREAD

**Issue by Aledati** [SunwellWoW/Sunwell-TBC-Bugtracker#2310] opened 2018-12-03 14:53 UTC
Description: 
Druid kitty dps with fast shapeshift changing forms.

How it works: 
Each time after changing forms in druid, cat/bear form makes cca 3 seconds pause and then start attacking.

How it should work: 
Each form has attack speed and autoattack should be according to attack speed without any pause.
This is crucial for cat dps, with this attack pause fast shapeshift changing dps is completely bad and not worthed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment] 2018-12-03 15:53
Druid resets his swing timer upon form changing. Give us some proofs that he shouldn't do that if you think so.

**Comment by Aledati** [comment] 2018-12-03 16:05
Dears,
Yes I agree but attack speed of cat is 1second without any haste rating not 3 seconds.If you want I will search for some proofs but I am 100% and more sure of this.
Best regards

**Comment by Aledati** [comment] 2018-12-03 17:30
Check this video on link please. Here you can see what I am talking about.
https://we.tl/t-5OEWFgSJOg

**Comment by 0vertime** [comment] 2018-12-03 19:37
Something is defo wrong here just can't pinpoint what. Maybe it's reading caster weaponspeed for next attack.

**Comment by Aledati** [comment] 2018-12-03 20:55
I dont know what is wrong, but also when cat miss/dodge/parry attack it gain some energy which should not be a case...should I open new ticket for that issue!?
Further when cat change indoor/outdoor zone movement speed stays as indoor until you do double shift in cat to reset outdoor speed...grrr also size of travel form cat is to big :D

**Comment by popalexandrudan** [comment] 2018-12-04 13:51
so also after playing to 46 druid i can confirm that the bug comes from the first attack that u do on a mob when u start fighting it, or after shapeshift. The first hit will have the melee attack speed of ur weapon, after its normal. Its not suppose to be like that !

**Comment by Grasswalker** [comment] 2018-12-04 21:49
Good evening, in the game i have 24lvl and from the beginning when i got a bear form i noticed that the change in form is not working properly. I played a druid on several servers, on Hellground where it worked correctly, the druid did not stop the attack when changing any form.
Druid feral rotation DPS is based on the macro "! Cat form" or a change of form for +40 energy and never attack should stop, it is a big minus in DPS and druid feral PvP.
Also changing the form from Cat to Bear, the attack form from Bear form should be immediately, next in 2.5 seconds(without haste in items).

" Wojtyas commented a day ago:
 Druid resets his swing timer upon form changing. Give us some proofs that he shouldn't do that if you think so. "

On Nightbane, fighting with an opponent and using macro "/ cast! Cat Form" or just going back and forth entering a cat form my druids in the form of a cat or a bear stops an animation of the attack for about two seconds, which proves that it should not be. There are several films on YT in the subject "feral TBC DPS" on different servers where we see these form changes without stopping the attack or attack animation.
I think that this is a priority matter to fix on the subject of druid fera, because it looks as if the warrior had a stop attack for 2 seconds when changing the stance or hunter when changing the aspect to stop shooting for 2 seconds...

**Comment by 0vertime** [comment] 2018-12-05 17:19
This is huge issue for feral. I'm positive its grabbing caster weapon speed for the next attack when going in form. Powershifting almost completely useless.

**Comment by Aledati** [comment] 2018-12-05 19:48
Anyone working on this? This should be high priority rly....as druid gets higher lvl this becomes very huge disadvantage...

**Comment by nimeral** [comment] 2018-12-07 23:33
Can confirm, the autoattack delay after shifting into cat form is like 3 seconds - probably indeed stems from my 2.8 staff.

**Comment by Wojtyas** [comment] 2018-12-08 08:42
Will be fixed soon

**Closed as completed** 2018-12-09 13:17 UTC
Labels: Fixed and Implemented.
