### ISSUE TITLE
[Npc] Mana Wyrm attacks after turning auto-attack on

### ISSUE THREAD

**Issue by Azathothh** [SunwellWoW/Sunwell-TBC-Bugtracker#316] opened 2018-09-06 13:51 UTC
Decription:  
[15:31:20]GUID: 54953.
[15:31:20]Faction: 7.
[15:31:20]npcFlags: 0.
[15:31:20]Entry: 15274.
[15:31:20]DisplayID: 16217 (Native: 16217).
[15:31:20]Level: 1.
[15:31:20]Health (base): 41. (max): 41. (current): 41.
[15:31:20]Field Flags: 0x00000800 Dynamic Flags: 0x00000000 Faction Template: 7.
[15:31:20]SpawnTime: Full:5m Remain:0s
[15:31:20]Loot: 15274 Pickpocket: 0 Skinning: 0
[15:31:20]InstanceID: 0
[15:31:20]Position: 10324.340820 -6301.533203 26.334782.
[15:31:20]XpMOD template: 1.000000
[15:31:20]XpMOD creature: 1.000000
[15:31:20]AIName: , ScriptName: mobs_mana_tapped
[15:31:20]DeadByDefault: 0
[15:31:20]Combat reach: 1.600000, BoundingRadius: 0.800000
[15:31:20]Determinative Size: 2.789927, CollisionWidth: 0.611100, Scale DB: 1.000000, Scale DBC: 1.600000
[15:31:20]Active flags: 0; Extra flags: 0x00000000
one of mana wyrms, but it's same with all of them
I've tried it with 10 different neutral mobs, like Springpaw Lynx, Feral Dragonhawk Hatchling  and this issue occured only with Mana Wyrms.

How it works: Those mobs are neutral, but when we turn on auto attack AND we are in their "aggro range" (in a range where they would attack us if they were hostile) they will attack us.

How it should work:  Neutral mobs should attack us only when we interract with them by actually attacking/using spells on them, turning on auto attack(without attacking) shouldn't make them hostile.

Source (you should point out proofs of your report, please give us some source): 
![obraz](https://user-images.githubusercontent.com/37483678/45161511-528a6580-b1ec-11e8-8865-368d02ccdb33.png)

**Comment by notsofamous** [comment] 2018-09-06 14:26
duplicate of: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/218

**Closed** 2018-09-06 14:30 UTC
Labels: Pathfinding / AI, duplicate
