### ISSUE TITLE
[Feral Druid] [Talent] Primal Fury not working

### ISSUE THREAD

**Issue by wildsure** [SunwellWoW/Sunwell-TBC-Bugtracker#3405] opened 2018-12-14 21:05 UTC
Description: 
Feral druid combo points are only awarding one combo point after a critical hit.

How it works: 
Using a combo point generating ability like mangle and getting a critical hit only gives one combo point (or at least the combo point graphic only shows one combo point)

How it should work: 
The talent "Primary Fury" should give a feral druid two combo points after a critical hit with a combo point generating ability like mangle.

Source (you should point out proofs of your report, please give us some source): 
Obvious from talent tooltip

**Comment by Cennas** [comment] 2018-12-15 01:21
The problem is also when u go up in the talent (atleast after reseting them) it only uses 1 point but says rank 2 as if u had used 2 talent points on it.

**Comment by zapsuu** [comment] 2018-12-15 08:05
Atm this talent completly not working for Mangle and Rake...

**Comment by Wojtyas** [comment] 2018-12-15 08:27
Related to https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/3399
Probably will be fixed with update. If not feel free to reopen ticket.

**Closed as completed by Wojtyas** 2018-12-15 08:27 UTC
Labels: Duplicate
